spring:
  application:
    name: payment-infra
#  config:
#    import:
#      - classpath:/application-core.yml
#  datasource:
#    url: jdbc:postgresql://localhost:5432/testdb
#    driver-class-name: org.postgresql.Driver
#    username: testuser
#    password: testpass
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create # or update / validate / none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console