spring:
  application:
    name: payment-infra

  datasource:
    jdbc:postgresql://localhost:5432/testdb
    url: jdbc:postgresql://postgres.db.svc.cluster.local:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: testuser
    password: testpass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update