apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  labels:
    app: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: payment-api
        image: ${DOCKER_REGISTRY}/payment-api:${IMAGE_TAG}
        ports:
        - containerPort: 9081
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        readinessProbe:
          tcpSocket:
            port: 9081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
spec:
  selector:
    app: payment-api
  ports:
  - port: 9081
    targetPort: 9081
  type: ClusterIP 