server:
  port: 8081

spring:
  profiles:
    active: local  # 기본값은 local
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: testuser
    password: testpass

  jpa:
    hibernate:
      ddl-auto: update

lifetime:
  qr: 180

time:
  zoneId: Asia/Seoul

jwt:
  secret: dYVzdC1zZWNyZXQta2V5LXlvdS2jYW4tY2hhbmdlPXRoaXM=

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
