# 개발 서버 환경 설정
spring:
  datasource:
    url: jdbc:postgresql://postgres-service.db.svc.cluster.local:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: testuser
    password: testpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false 