name: Backoffice API CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backoffice-api/**'
      - '.github/workflows/backoffice-api-cicd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backoffice-api/**'
      - '.github/workflows/backoffice-api-cicd.yml'

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_DEPLOY_PATH: ${{ secrets.SERVER_DEPLOY_PATH }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew :backoffice-api:build -x test

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ env.SERVER_SSH_KEY }}

    - name: Deploy to Server
      run: |
        # SSH 키 권한 설정
        mkdir -p ~/.ssh
        echo "${{ env.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # 서버에 JAR 파일 전송
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no backoffice-api/build/libs/*.jar ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_DEPLOY_PATH }}/backoffice-api.jar
        
        # 서버에서 애플리케이션 재시작
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} '
          sudo systemctl stop backoffice-api
          sleep 5
          sudo systemctl start backoffice-api
        '

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,message,author
        custom_payload: |
          {
            "attachments": [{
              "color": "#439FE0",
              "text": ":rocket: *Push 감지됨!*\n브랜치: `${{ github.ref_name }}`\n커밋 메시지: `${{ github.event.head_commit.message }}`\n작성자: `${{ github.actor }}`"
            }]
          }
        author_name: GitHub Actions
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() 