name: Backoffice API CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backoffice-api/**'
      - '.github/workflows/backoffice-api-cicd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backoffice-api/**'
      - '.github/workflows/backoffice-api-cicd.yml'

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_DEPLOY_PATH: ${{ secrets.SERVER_DEPLOY_PATH }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew :backoffice-api:build -x test

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ env.SERVER_SSH_KEY }}

    - name: Deploy to Server
      run: |
        # SSH 키 권한 설정
        mkdir -p ~/.ssh
        echo "${{ env.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # 서버에 JAR 파일 전송
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no backoffice-api/build/libs/*.jar ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_DEPLOY_PATH }}/backoffice-api.jar
        
        # 서버에서 애플리케이션 재시작
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} '
          cd ${{ env.SERVER_DEPLOY_PATH }} && \
          if [ -f backoffice-api.pid ]; then \
            kill $(cat backoffice-api.pid) || true; \
            rm backoffice-api.pid; \
          fi && \
          nohup java -jar backoffice-api.jar > backoffice-api.log 2>&1 & \
          echo $! > backoffice-api.pid
        ' 