name: Deploy to Production Server

on:
  push:
    branches:
      - main
      - temp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 배포 디렉토리로 이동
            cd ${{ secrets.DEPLOY_DIR }}

            # 깃 저장소 업데이트
            git fetch
            git checkout -f ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}

            # gradlew에 실행 권한 부여
            chmod +x ./gradlew

            # 애플리케이션 빌드
            ./gradlew build -x test

            # payment-method 모듈 먼저 빌드
            ./gradlew :payment-method:build -x test
            
            # payment 애플리케이션 재시작
            if [ -f payment.pid ]; then
              kill $(cat payment.pid) || true
              rm payment.pid
            fi
            rm -f payment/build/libs/*.jar
            ./gradlew :payment:build -x test
            PAYMENT_JAR=$(find payment/build/libs -name "payment-*.jar" ! -name "*plain.jar" | sort | tail -1)
            nohup java -jar $PAYMENT_JAR > payment.log 2>&1 & echo $! > payment.pid

            # backoffice-api 애플리케이션 재시작
            if [ -f backoffice-api.pid ]; then
              kill $(cat backoffice-api.pid) || true
              rm backoffice-api.pid
            fi
            rm -f backoffice-api/build/libs/*.jar
            ./gradlew :backoffice-api:build -x test
            BACKOFFICE_API_JAR=$(find backoffice-api/build/libs -name "backoffice-api-*.jar" ! -name "*plain.jar" | sort | tail -1)
            nohup java -jar $BACKOFFICE_API_JAR > backoffice-api.log 2>&1 & echo $! > backoffice-api.pid

            # backoffice-manage 애플리케이션 재시작
            if [ -f backoffice-manage.pid ]; then
              kill $(cat backoffice-manage.pid) || true
              rm backoffice-manage.pid
            fi
            export yaml="${{ secrets.BM }}"
            echo "$yaml" > backoffice-manage/src/main/resources/application.yml
            rm -f backoffice-manage/build/libs/*.jar
            ./gradlew :backoffice-manage:build -x test
            BACKOFFICE_MANAGE_JAR=$(find backoffice-manage/build/libs -name "backoffice-manage-*.jar" ! -name "*plain.jar" | sort | tail -1)
            nohup java -jar $BACKOFFICE_MANAGE_JAR > backoffice-manage.log 2>&1 & echo $! > backoffice-manage.pid

            # appuser-manage 애플리케이션 재시작
            if [ -f appuser-manage.pid ]; then
              kill $(cat appuser-manage.pid) || true
              rm appuser-manage.pid
            fi
            export yaml="${{ secrets.UM }}"
            echo "$yaml" > appuser-manage/src/main/resources/application.yml
            rm -f appuser-manage/build/libs/*.jar
            ./gradlew :appuser-manage:build -x test
            APPUSER_MANAGE_JAR=$(find appuser-manage/build/libs -name "appuser-manage-*.jar" ! -name "*plain.jar" | sort | tail -1)
            nohup java -jar $APPUSER_MANAGE_JAR > appuser-manage.log 2>&1 & echo $! > appuser-manage.pid


            echo "모든 모듈 배포 및 재시작 완료"
